métodos gerais:

* pd.read()
* df.describe()
* df.info()
* df.dropna()
* df.drop()
* df.fillna()
* pd.to_datetime()

<h3>Leitura de Arquivos</h3>

In [3]:
import numpy as np
import pandas as pd

df_vendas = pd.read_csv('vendas_tech.csv', low_memory=False)
df_gerentes = pd.read_excel('gerentes_lojas.xlsx')

# Configura para mostrar no MÁXIMO 20 linhas
pd.set_option('display.max_rows', 15)

# Configura para mostrar no MÁXIMO 50 colunas (evita barra de rolagem infinita lateral)
pd.set_option('display.max_columns', 50)

display(df_vendas.head(15))
display(df_gerentes)

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

anotações:

parametros do read:
encoding= (utf-8, latin1,), para decodificar acentos etc
sep = ( ; , ), Separação das informações csv
low_memory = ( true, false), consumir memória para separar os tipos de dados str floatetc

In [ ]:
#ferramentas de inspeção

display(df_vendas)
#display(df_vendas.head(5)) ver as n primeiras linhas
#display(df_vendas.tail(5)) ver as n primeiras linhas
# display(df_vendas.sample(5)) ver 5 aleatórias
display(df_vendas.shape) # linhas x colunas
display(list(df_vendas.columns)) # lista das colunas

In [ ]:
display(df_vendas.info()) # info gerais
print('\n')
print('\n')
display(df_vendas.describe()) # descrição detalhada

<h3>Tratamento de dados</h3>

In [ ]:
display(df_vendas['Loja'])

display(df_vendas[['Loja', 'Cliente']]) # Deve ser uma LISTA DE COLUNAS

<h3>Tratamento de Colunas</h3>

In [9]:
df_vendas_analise = df_vendas.drop(columns=['Data_Base']) # Excluir linhas ou colunas

display(df_vendas_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

para retirar posso ou passar as listas de colunas desejadas como indice ou
df.drop(), o parametro deve ser uma lista com as colunas a retirar

<h3>Eliminar valores Nulos</h3>

In [10]:
display(df_vendas_analise.info()) #Ver colunas com NaN
display('\n')

#DELETAR LINHAS COM QUALQUER NAN
df_vendas_analise = df_vendas_analise.dropna() 

display(df_vendas_analise)
display('\n')

# TRATAR APENAS OS VALORES NAN DA COLUNA LOJA
df_vendas_analise = df_vendas.drop(columns=['Data_Base'])
df_vendas_analise['Loja'] = df_vendas['Loja'].fillna('Online') # Coloca o valor do parametro no lugar do nan

display(df_vendas_analise)

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
dtypes: float64(1), int64(2), str(4)
memory usage: 5.3 MB

None

'\n'

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

'\n'

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

<h3>Tipos de Dados Diferentes</h3>

In [11]:
#Transformando a coluna de data em datas reais

df_vendas_analise['Data'] = pd.to_datetime(df_vendas_analise['Data'], format='%Y-%m-%d')

display(df_vendas_analise)
display(df_vendas_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  datetime64[us]
 2   Loja            100100 non-null  str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

<h3>Padronização / Formatação</h3>

In [12]:
df_vendas_analise['Loja'] = df_vendas_analise['Loja'].str.strip()
df_vendas_analise['Loja'] = df_vendas_analise['Loja'].str.title()

display(df_vendas_analise.head(20))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508
10,11,2023-06-28,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_3253
11,12,2024-01-29,Rio De Janeiro,Mouse Gamer,120.0,1,Cliente_586
12,13,2024-06-25,Recife,Smartphone Samsung,2200.0,1,Cliente_4301
13,14,2023-04-13,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_22985
14,15,2023-06-23,Curitiba,Cabo HDMI,40.0,1,Cliente_27383
15,16,2024-04-04,Curitiba,"Monitor 27""",1200.0,1,Cliente_12891
16,17,2023-06-16,Rio De Janeiro,iPhone 14,5500.0,1,Cliente_28162
17,18,2023-07-06,Curitiba,Cabo HDMI,40.0,1,Cliente_24451
18,19,2024-03-20,Salvador,Cabo HDMI,40.0,1,Cliente_4793
19,20,2024-08-15,Belo Horizonte,Smartphone Samsung,2200.0,3,Cliente_27943

<h3>Remover Duplicatas</h3>

In [13]:
df_vendas_analise = df_vendas_analise.drop_duplicates(subset=['ID_Pedido', 'Loja'], keep='last')
display(df_vendas_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

subset : colunas para considerar iguais
keep : first ou last, remover primeira ou segunda duplicata

<h3>Criar Novas Colunas</h3>

In [14]:
df_vendas_analise['Faturamento'] = df_vendas_analise['Qtd'] * df_vendas_analise['Preco_Unitario']
display(df_vendas_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,5500.0
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,7000.0
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,4400.0
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,11000.0
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,6400.0

<h3>Condicionais / Tratamento</h3>

In [15]:
df_vendas_loja = df_vendas_analise.groupby('Loja').agg({'Cliente':'count', 'Faturamento':'sum'})

print(df_vendas_loja)

                Cliente  Faturamento
Loja
Belo Horizonte    13965   41714890.0
Curitiba          13901   41121720.0
Online             2001    6080850.0
Porto Alegre      13884   41678460.0
Recife            14113   42190390.0
Rio De Janeiro    14099   42294720.0
Salvador          14024   42300610.0
São Paulo         14013   42090690.0

In [16]:
df_vendas_analise['Forma_De_Venda'] = np.where(df_vendas_analise['Loja'] == 'Online', 'Online', 'Presencial')
display(df_vendas_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_De_Venda
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial
...,...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,5500.0,Presencial
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,7000.0,Presencial
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,4400.0,Presencial
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,11000.0,Presencial
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,6400.0,Presencial

In [ ]:
display(df_vendas_analise['Loja'].unique())

sudeste = ['São Paulo', 'Belo Horizonte', 'Rio de Janeiro']
nordeste = ['Salvador', 'Recife']
sul = ['Curitiba', 'Porto Alegre']

dict_regioes = {
    'São Paulo': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Online' : 'Online',
    'Rio De Janeiro': 'Sudeste',
    'Salvador' : 'Nordeste',
    'Recife' : 'Nordeste',
    'Curitiba' : 'Sul',
    'Porto Alegre' : 'Sul',
}

#df_vendas_analise['Região'] = np.where(df_vendas_analise['Loja'] in sudeste, 'Sudeste', np.where(...)) JEITO 1
df_vendas_analise['Região'] = df_vendas_analise['Loja'].map(dict_regioes)

display(df_vendas_analise)

<h3>Exportar Pedaços da Tabela / Filtrar</h3>

In [ ]:
df_vendas_analise = df_vendas_analise.sort_values(by=['Data', 'Faturamento'], ascending=True)

loja = df_vendas_analise.loc[4, 'Loja']
produto = df_vendas_analise.loc[4, 'Produto']
cliente = df_vendas_analise.loc[4, 'Cliente']
print(loja, produto, cliente)

In [ ]:
loja = df_vendas_analise.iloc[4, 2]
produto = df_vendas_analise.iloc[4, 3]
cliente = df_vendas_analise.iloc[4, 6]
print(loja, produto, cliente)

display(df_vendas_analise)

In [ ]:
df_vendas_analise = df_vendas_analise.reset_index(drop=True)
display(df_vendas_analise)

* df.loc - Localizar informação especifica com index e coluna
* df.iloc(index, index-coluna) - Localizar informação especifica com index e index da coluna

<h3>Filtrando com Condicional</h3>

In [ ]:
display(df_vendas_analise)

df_id_4 = df_vendas_analise[df_vendas_analise['ID_Pedido'] == 4]
display(df_id_4)

loja = df_vendas_analise.loc[df_vendas_analise['ID_Pedido'] == 4, 'Loja']#.values[0] transforma em array e pega só o nome
display(loja)

In [ ]:
df_vendas_sp = df_vendas_analise[df_vendas_analise['Loja'] == 'São Paulo']

display(df_vendas_sp)

df_vendas_sp = df_vendas_sp.reset_index(drop=True)

display(df_vendas_sp)

df_vendas_sp.to_csv('Vendas_sp.csv')
df_vendas_sp.to_csv('Vendas_sp_semindex.csv', index=False)

In [ ]:
df_vendas_2024 = df_vendas_analise[df_vendas_analise['Data'].dt.year == 2024]
display(df_vendas_2024)

df_vendas_hdmi_sul = df_vendas_analise[(df_vendas_analise['Produto'] == 'Cabo HDMI') & (df_vendas_analise['Região'] == 'Sul')]
display(df_vendas_hdmi_sul)

<h3>Análise com Agrupamento</h3>

In [ ]:
#df_analise_loja = df_vendas_analise.groupby('Loja')['Faturamento'].sum()
df_analise_loja = df_vendas_analise[['Loja', 'Faturamento']].groupby('Loja').sum().sort_values(by='Faturamento', ascending=False)
df_analise_loja = df_analise_loja.reset_index()
df_analise_loja['Faturamento'] = df_analise_loja['Faturamento'].map(lambda x : f'R${x:,.2f}')
display(df_analise_loja)

In [ ]:
df_vendas_online = df_vendas_analise[df_vendas_analise['Loja'] == 'Online']
df_vendas_online = df_vendas_online[['Produto', 'Qtd']].groupby('Produto').sum().sort_values(by='Qtd', ascending=False)

df_vendas_online = df_vendas_online.rename(columns={'Qtd':'Vendas Totais'})

display(df_vendas_online)

In [ ]:
df_vendas_por_loja = df_vendas_analise[['Loja', 'Produto', 'Qtd']].groupby(['Loja', 'Produto']).sum()

with pd.option_context('display.max_rows', None):
    display(df_vendas_por_loja)

In [ ]:
df_nsei = df_vendas_analise[['Loja', 'Produto', 'Qtd']].groupby(['Produto', 'Loja']).sum().sort_values(by=['Produto', 'Qtd'], ascending=[True, False])

df_nsei.to_csv('produto_por_regiao.csv')

with pd.option_context('display.max_rows', None):
    display(df_nsei)

In [ ]:
#display(df_vendas_analise.head())

# quais gerentes bateram a meta em janeiro de 23

#display(df_gerentes)

df_meta = df_vendas_analise[(df_vendas_analise['Data'].dt.year == 2023) & (df_vendas_analise['Data'].dt.month == 1)]

df_meta = df_meta[['Faturamento','Loja']].groupby(['Loja']).sum()

df_meta = df_meta.reset_index(drop=False)

df_meta = df_meta.sort_values(by=['Loja'], ascending=True)

df_meta_gerentes = pd.merge(df_meta, df_gerentes, how='left', on='Loja') #esse e o de baixo fazem o mesmo

display(df_meta_gerentes)

df_meta_gerentes = df_meta.merge(df_gerentes, on='Loja', how='left') #esse e o de baixo fazem o mesmo

display(df_meta_gerentes)

# NAO ENCONTRA RJ PELA DIFERENÇA DE FORMATAÇÂO

df_gerentes['Loja'] = df_gerentes['Loja'].str.strip().str.title()

display(df_gerentes)

df_meta_gerentes = df_meta.merge(df_gerentes, on='Loja', how='left') 

df_meta_gerentes['Bateu_Meta'] = np.where(df_meta_gerentes['Faturamento'] >= df_meta_gerentes['Meta_Mensal'], 'Sim', 'Não')

display(df_meta_gerentes)

In [ ]:
display(df_vendas_analise)

df_vendas_analise['Mes-Ano'] = df_vendas_analise['Data'].dt.to_period('M')

display(df_vendas_analise)

df_vendas_mes = df_vendas_analise[['Mes-Ano', 'Faturamento']].groupby(['Mes-Ano']).sum()

display(df_vendas_mes)

df_vendas_mes.plot()