Métodos gerais

* df.groupby()
* df.agg()
* df.sort_values()
* pd.merge()

<h3>Fundamentos de Pandas</h3>

In [2]:
import pandas as pd
import numpy as np

dados = {
    'Produto': ['Celular', 'Notebook', 'Tablet', 'Fone'],
    'Preco': [2000, 5000, 1500, 300],
    'Quantidade': [10, 5, 20, 50]
}

df = pd.DataFrame(dados)

print(df)
print('\n')

print(df['Preco'])

    Produto  Preco  Quantidade
0   Celular   2000          10
1  Notebook   5000           5
2    Tablet   1500          20
3      Fone    300          50


0    2000
1    5000
2    1500
3     300
Name: Preco, dtype: int64

In [3]:
#Criando faturamento

df['Faturamento'] = df['Preco'] * df['Quantidade']

print(df)
print('\n')

print(df.describe())

    Produto  Preco  Quantidade  Faturamento
0   Celular   2000          10        20000
1  Notebook   5000           5        25000
2    Tablet   1500          20        30000
3      Fone    300          50        15000


             Preco  Quantidade   Faturamento
count     4.000000    4.000000      4.000000
mean   2200.000000   21.250000  22500.000000
std    1998.332638   20.155644   6454.972244
min     300.000000    5.000000  15000.000000
25%    1200.000000    8.750000  18750.000000
50%    1750.000000   15.000000  22500.000000
75%    2750.000000   27.500000  26250.000000
max    5000.000000   50.000000  30000.000000

<h3>Agrupamento</3>

In [4]:
import pandas as pd

# 1. Dados mais complexos (Várias vendas do mesmo item)
dados = {
    'Categoria': ['Eletrônicos', 'Eletrônicos', 'Móveis', 'Móveis', 'Eletrônicos', 'Móveis', 'Móveis'],
    'Produto': ['Celular', 'Notebook', 'Mesa', 'Cadeira', 'Celular', 'Mesa', 'Cadeira'],
    'Vendas': [2000, 5000, 500, 200, 2200, 400, 500]
}
df = pd.DataFrame(dados)

print("--- Tabela Original ---")
print(df)
print("\n")

# 2. A MÁGICA DO GROUPBY
# Agrupe por 'Categoria' e some as 'Vendas'
df_agrupado = df.groupby('Categoria')

resumo = df_agrupado['Vendas'].sum()

print("--- Resumo por Categoria ---")
print(resumo)
print('\n')

# Agrupe por 'Produto' e somea as vendas

venda_por_produto = df.groupby('Produto')['Vendas'].agg(['sum', 'count'])

print(venda_por_produto)

--- Tabela Original ---
     Categoria   Produto  Vendas
0  Eletrônicos   Celular    2000
1  Eletrônicos  Notebook    5000
2       Móveis      Mesa     500
3       Móveis   Cadeira     200
4  Eletrônicos   Celular    2200
5       Móveis      Mesa     400
6       Móveis   Cadeira     500


--- Resumo por Categoria ---
Categoria
Eletrônicos    9200
Móveis         1600
Name: Vendas, dtype: int64


           sum  count
Produto
Cadeira    700      2
Celular   4200      2
Mesa       900      2
Notebook  5000      1

<h3>Agregate</h3>

In [5]:
relatorio_completo = df.groupby('Categoria')['Vendas'].agg(['sum', 'mean', 'count'])

print(relatorio_completo)

              sum         mean  count
Categoria
Eletrônicos  9200  3066.666667      3
Móveis       1600   400.000000      4

In [6]:
relatorio_completo = df.groupby('Produto')['Vendas'].agg(['sum', 'mean', 'max', 'min', 'count', 'idxmax'])

print(relatorio_completo)

           sum    mean   max   min  count  idxmax
Produto
Cadeira    700   350.0   500   200      2       6
Celular   4200  2100.0  2200  2000      2       4
Mesa       900   450.0   500   400      2       2
Notebook  5000  5000.0  5000  5000      1       1

In [7]:
dados = {
    'Categoria': ['Eletrônicos', 'Eletrônicos', 'Móveis', 'Móveis', 'Eletrônicos'],
    'Produto': ['Celular', 'Notebook', 'Mesa', 'Cadeira', 'Celular'],
    'Vendas': [2000, 5000, 500, 200, 2200],
    'Quantidade Por Venda': [2, 1, 4, 10, 2]
}
df = pd.DataFrame(dados)

print(df)
print('\n')

grupo_produto = df.groupby('Produto')['Vendas'].agg(['sum', 'count'])

print(grupo_produto)
print('\n')

relatorio = df.groupby('Categoria').agg({
    'Vendas': ['sum', 'count', 'mean'],   
    'Quantidade Por Venda': ['sum', 'count', 'mean'] 
})

print(relatorio)

     Categoria   Produto  Vendas  Quantidade Por Venda
0  Eletrônicos   Celular    2000                     2
1  Eletrônicos  Notebook    5000                     1
2       Móveis      Mesa     500                     4
3       Móveis   Cadeira     200                    10
4  Eletrônicos   Celular    2200                     2


           sum  count
Produto
Cadeira    200      1
Celular   4200      2
Mesa       500      1
Notebook  5000      1


            Vendas                    Quantidade Por Venda
               sum count         mean                  sum count      mean
Categoria
Eletrônicos   9200     3  3066.666667                    5     3  1.666667
Móveis         700     2   350.000000                   14     2  7.000000

In [8]:
desafio = df.groupby('Produto').agg({
    'Vendas': 'min', 'Quantidade Por Venda' : 'sum'
})

print(desafio)

          Vendas  Quantidade Por Venda
Produto
Cadeira      200                    10
Celular     2000                     4
Mesa         500                     4
Notebook    5000                     1

<h3>Ordem crescente e decrescente / sort_values() </h3>

In [9]:
ranking = venda_por_produto.sort_values(by='',ascending=False)

print(ranking)

KeyError: ''

In [ ]:
ranking = venda_por_produto.sort_values(ascending=True)

print(ranking)

<h3>Merge</h3>

In [ ]:
vendas = pd.DataFrame({
    'Data': ['01/01', '02/01', '03/01', '03/01'],
    'Produto': ['Celular', 'Notebook', 'Celular', 'Fone'],
    'Valor': [2000, 5000, 3000, 300],
    'id_cliente': [1, 2, 1, 3]  
})

clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4],
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Email': ['joao@email.com', 'maria@email.com', 'pedro@email.com', 'ana@email.com']
})

print("--- Vendas ---")
print(vendas)
print("\n--- Clientes ---")
print(clientes)

In [ ]:
vendas_completas = pd.merge(vendas, clientes, on='id_cliente', how='left')

print(vendas_completas)
print('\n')

vendas_completas = pd.merge(clientes, vendas, on='id_cliente', how='left')

print(vendas_completas)

In [10]:
display(df)
df['Status'] = np.where(df['Vendas']>3000, 'Alta', 'Normal')

df['Categoria_'] = df['Produto'].apply(lambda x : 'C-Type' if x[0] == 'C' else 'Outros')

display(df)

relatorio = df.pivot_table(index='Categoria',
                            columns='Produto',
                            values='Vendas',
                            aggfunc='sum',
                            fill_value=0,
                            margins=True,
                            margins_name='Total Geral')

display(relatorio)

     Categoria   Produto  Vendas  Quantidade Por Venda
0  Eletrônicos   Celular    2000                     2
1  Eletrônicos  Notebook    5000                     1
2       Móveis      Mesa     500                     4
3       Móveis   Cadeira     200                    10
4  Eletrônicos   Celular    2200                     2

     Categoria   Produto  Vendas  Quantidade Por Venda  Status Categoria_
0  Eletrônicos   Celular    2000                     2  Normal     C-Type
1  Eletrônicos  Notebook    5000                     1    Alta     Outros
2       Móveis      Mesa     500                     4  Normal     Outros
3       Móveis   Cadeira     200                    10  Normal     C-Type
4  Eletrônicos   Celular    2200                     2  Normal     C-Type

Produto      Cadeira  Celular  Mesa  Notebook  Total Geral
Categoria
Eletrônicos        0     4200     0      5000         9200
Móveis           200        0   500         0          700
Total Geral      200     4200   500      5000         9900

In [ ]:
df_porcentagem = df[['Vendas', 'Categoria']].groupby('Categoria').sum()

display(df_porcentagem)

df_porcentagem['%'] = df_porcentagem['Vendas'] / df_porcentagem['Vendas'].sum()

df_porcentagem['%'] = df_porcentagem['%'].apply( lambda x : (x*100))

display(df_porcentagem)